version: "3.3"
services:
  my-app-db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "BiBiGame"
      POSTGRES_USER: "BiBiGame"
      POSTGRES_PASSWORD: "BiBiGame"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      #- ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U 'BiBiGame' -d 'BiBiGame'" ]
      interval: 10s
      timeout: 5s
      retries: 5
