FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 81
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY ["Api/Api.csproj", "Api/"]
RUN dotnet restore "Api/Api.csproj"
COPY . .
WORKDIR "/src/Api"
RUN dotnet build "Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api.dll"]



RUN apt-get update \\
    && apt-get install -y letsencrypt -t jessie-backports \\
    && apt-get clean \\ && rm -rf /var/lib/apt/lists/* \\
    && mkdir -p /etc/letsencrypt/live/my.example.org \\
    && openssl req -x509 -nodes -days 365 -newkey rsa:2048 \\
        -keyout /etc/letsencrypt/live/my.example.org/privkey.pem \\
        -out /etc/letsencrypt/live/my.example.org/fullchain.pem \\
        -subj /CN=my.example.org
