version: "3.3"
services:
  my-app: 
    image: my-app:1
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: 13Friends)
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/api.pfx
    ports:
      # Replace the values on the left by the values on your launchSettings.json
      - "5000"
      - "5001"
    volumes:
      - ~/.aspnet/https:/https:ro
